--------------------------------------------------------
--  File created - Wednesday-March-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DISEASES
--------------------------------------------------------

  CREATE TABLE "MADALINA"."DISEASES" 
   (	"ID" NUMBER, 
	"DISEASE_NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"SALT" NUMBER, 
	"SUGAR" NUMBER, 
	"FATS" NUMBER, 
	"CARBOHYDRATE" NUMBER, 
	"FIBER" NUMBER, 
	"PROTEIN" NUMBER, 
	"CALORIES" NUMBER, 
	"SATURATES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENUMBER
--------------------------------------------------------

  CREATE TABLE "MADALINA"."ENUMBER" 
   (	"ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"TECHNOLOGICAL_FUNCTION" VARCHAR2(50 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"DANGER_LEVEL" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FEEDBACK
--------------------------------------------------------

  CREATE TABLE "MADALINA"."FEEDBACK" 
   (	"USER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"RATING" NUMBER(5,0) DEFAULT 0, 
	"MESSAGE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "MADALINA"."PRODUCTS" 
   (	"BAR_CODE" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"SALT" NUMBER, 
	"SUGAR" NUMBER, 
	"FATS" NUMBER, 
	"CARBOHYDRATE" NUMBER, 
	"FIBER" NUMBER, 
	"PROTEIN" NUMBER, 
	"CALORIES" NUMBER, 
	"SATURATES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECIPES
--------------------------------------------------------

  CREATE TABLE "MADALINA"."RECIPES" 
   (	"ID" NUMBER, 
	"RECIPE_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"METHOD_OF_PREPARATION" VARCHAR2(1000 BYTE), 
	"SALT" NUMBER, 
	"SUGAR" NUMBER, 
	"FATS" NUMBER, 
	"CARBOHYDRATE" NUMBER, 
	"FIBER" NUMBER, 
	"PROTEIN" NUMBER, 
	"CALORIES" NUMBER, 
	"SATURATES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECIPE_COMPONENTS
--------------------------------------------------------

  CREATE TABLE "MADALINA"."RECIPE_COMPONENTS" 
   (	"RECIPE_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "MADALINA"."TEST" 
   (	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MADALINA"."USERS" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_DISEASE
--------------------------------------------------------

  CREATE TABLE "MADALINA"."USER_DISEASE" 
   (	"USER_ID" NUMBER, 
	"DISEASE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into MADALINA.DISEASES
SET DEFINE OFF;
REM INSERTING into MADALINA.ENUMBER
SET DEFINE OFF;
REM INSERTING into MADALINA.FEEDBACK
SET DEFINE OFF;
REM INSERTING into MADALINA.PRODUCTS
SET DEFINE OFF;
REM INSERTING into MADALINA.RECIPES
SET DEFINE OFF;
REM INSERTING into MADALINA.RECIPE_COMPONENTS
SET DEFINE OFF;
REM INSERTING into MADALINA.TEST
SET DEFINE OFF;
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Gica','Popescu');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Madalina','Ionescu');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Ion','Simion');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Larisa','Gigel');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Irina','Vale');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Alexandru','Plop');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Ana-Maria','Lungu');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Gabi','Talmaciu');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Ludovic','Ursan');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Dorel','Olanuta');
Insert into MADALINA.TEST (FIRST_NAME,LAST_NAME) values ('Vlad','Coifu');
REM INSERTING into MADALINA.USERS
SET DEFINE OFF;
REM INSERTING into MADALINA.USER_DISEASE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FEEDBACK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."FEEDBACK_PK" ON "MADALINA"."FEEDBACK" ("USER_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."USERS_PK" ON "MADALINA"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENUMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."ENUMBER_PK" ON "MADALINA"."ENUMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."PRODUCTS_PK" ON "MADALINA"."PRODUCTS" ("BAR_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DISEASES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."DISEASES_PK" ON "MADALINA"."DISEASES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."USERS_EMAIL" ON "MADALINA"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DISEASE_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."DISEASE_NAME" ON "MADALINA"."DISEASES" ("DISEASE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECIPE_COMPONENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."RECIPE_COMPONENTS_PK" ON "MADALINA"."RECIPE_COMPONENTS" ("RECIPE_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECIPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."RECIPES_PK" ON "MADALINA"."RECIPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_DISEASE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MADALINA"."USER_DISEASE_PK" ON "MADALINA"."USER_DISEASE" ("USER_ID", "DISEASE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RECIPES
--------------------------------------------------------

  ALTER TABLE "MADALINA"."RECIPES" ADD CONSTRAINT "RECIPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."RECIPES" MODIFY ("METHOD_OF_PREPARATION" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."RECIPES" MODIFY ("RECIPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."RECIPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECIPE_COMPONENTS
--------------------------------------------------------

  ALTER TABLE "MADALINA"."RECIPE_COMPONENTS" ADD CONSTRAINT "RECIPE_COMPONENTS_PK" PRIMARY KEY ("RECIPE_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."RECIPE_COMPONENTS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."RECIPE_COMPONENTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."RECIPE_COMPONENTS" MODIFY ("RECIPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENUMBER
--------------------------------------------------------

  ALTER TABLE "MADALINA"."ENUMBER" ADD CONSTRAINT "ENUMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."ENUMBER" MODIFY ("DANGER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."ENUMBER" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."ENUMBER" MODIFY ("TECHNOLOGICAL_FUNCTION" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."ENUMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."ENUMBER" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."ENUMBER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_DISEASE
--------------------------------------------------------

  ALTER TABLE "MADALINA"."USER_DISEASE" ADD CONSTRAINT "USER_DISEASE_PK" PRIMARY KEY ("USER_ID", "DISEASE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."USER_DISEASE" MODIFY ("DISEASE_ID" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."USER_DISEASE" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FEEDBACK
--------------------------------------------------------

  ALTER TABLE "MADALINA"."FEEDBACK" ADD CONSTRAINT "FEEDBACK_PK" PRIMARY KEY ("USER_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."FEEDBACK" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."FEEDBACK" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."FEEDBACK" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MADALINA"."USERS" ADD CONSTRAINT "USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "MADALINA"."TEST" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."TEST" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "MADALINA"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("BAR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."PRODUCTS" MODIFY ("BAR_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISEASES
--------------------------------------------------------

  ALTER TABLE "MADALINA"."DISEASES" ADD CONSTRAINT "DISEASE_NAME" UNIQUE ("DISEASE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."DISEASES" ADD CONSTRAINT "DISEASES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MADALINA"."DISEASES" MODIFY ("DISEASE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MADALINA"."DISEASES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Function RANDOM_STR
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "MADALINA"."RANDOM_STR" (v_length number) return varchar2 is
    my_str varchar2(4000);
begin
    for i in 1..v_length loop
        my_str := my_str || dbms_random.string(
            case when dbms_random.value(0, 1) < 0.5 then 'l' else 'x' end, 1);
    end loop;
    return my_str;
end;

/
